[package]
name = "platformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# remember to disable "dynamic" feature before release
bevy = { version = "0.6.0", features = ["dynamic"] }
